#!/bin/bash

DIR_PATH="$1"
EXPORT_FOLDER="$2"
FILE_FOLDER="$3"
BUNDLE_PATH="$4"
FILENAME="$5"
SCALE="$6"


cd "$DIR_PATH"
mkdir -p "$EXPORT_FOLDER"

# move old artboards to temp directory to compare them with the new ones
rm -rf .oldArtboards
mv "$FILE_FOLDER" .oldArtboards 2>/dev/null

# get list of artboards regex to ignore
IGNORE=$([ -e .sketchignore ] && (cat .sketchignore | sed '/^$/d' | sed 's/^/^/' | sed 's/$/$/' | tr '\n' ',') || echo "")

# get list of artboard names to export
ARTBOARDS=$($BUNDLE_PATH/Contents/Resources/sketchtool/bin/sketchtool list artboards "$FILENAME" --include-symbols=YES | python "$(dirname "$0")"/getArtboardNames.py "$IGNORE" | tr '\n' ',')


# generate new artboards
mkdir -p "$FILE_FOLDER"
$BUNDLE_PATH/Contents/Resources/sketchtool/bin/sketchtool export artboards "$FILENAME" --scales="$SCALE" --output="$FILE_FOLDER" --overwriting=YES --items="$ARTBOARDS" --include-symbols=YES

# Construct a README.md file which shows all the artboards in the sketch directory
README_FILE="./${FILENAME%.*}-boards.md" # Exclude the file extension
echo "# Artboards" > ${README_FILE}
echo "" >> ${README_FILE}
echo "This is an autogenerated file showing all the artboards. Do not edit it directly." >> ${README_FILE}

# compare new artboards with the old ones
for artboardPath in "$FILE_FOLDER"/*
do
  artboard=$(basename "$artboardPath")
  if [[ -f .oldArtboards/"$artboard" ]]; then
    # Get base64 encoded artboard
    newArtboard="$(cat "$FILE_FOLDER"/"$artboard" | base64)"
    oldArtboard="$(cat .oldArtboards/"$artboard" | base64)"

    # See if the artboards are the same
    if [ "$newArtboard" == "$oldArtboard" ]; then
      # keep the old artboard
      rm "$artboardPath"
    	mv .oldArtboards/"$artboard" "$artboardPath"
    fi
  fi

  artboardName="${artboard%.*}" # Exclude the file extension
  echo "" >> ${README_FILE}
  echo "## ${artboardName}" >> ${README_FILE}
  echo "" >> ${README_FILE}
  echo "![${artboardName}](./${artboardPath})" >> ${README_FILE}
  echo "" >> ${README_FILE}
done


git add "$EXPORT_FOLDER"
git add "${README_FILE}"
rm -rf .oldArtboards
